# Generated by Django 3.2.5 on 2025-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_issue_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
